spring.application.name=smart-fridge-service
server.port=8080

spring.graphql.graphiql.enabled=true
spring.graphql.path=/graphql
spring.graphql.schema.locations=classpath*:graphql/
dgs.graphql.schema-locations=classpath*:graphql/**/*.graphqls
spring.graphql.schema.introspection.enabled=true