spring:
  application:
    name: smart-fridge-notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000
          multiplier: 2


server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info